### ISSUE TITLE
wtreg function error

### ISSUE THREAD

**Issue by KenishaS** [fawda123/WtRegDO#3]
I'm experiencing an error when I run the wtreg function using the SAPDC sample dataset and with my own dataset as well.  I think the source of the error is totpar = ref_in$totpar[x] in line 142.  I've attached two screenshots for reference, one that shows the sample SAPDC run with the error and then the error code I get when I run my dataset.  Thanks!

![SAPDC_screenshot](https://user-images.githubusercontent.com/90009032/131924933-30ddcc6b-c4de-49e0-b160-bac3a9083978.png)
![AHLdataset_error code](https://user-images.githubusercontent.com/90009032/131924944-455dd786-9fe0-471c-b72c-55cfeed263c5.png)

**Comment by fawda123** [comment]
Hi, 

Can you try installing the package from here?  

```
options(repos = c(
    fawda123 = 'https://fawda123.r-universe.dev',
    CRAN = 'https://cloud.r-project.org'))

install.packages('WtRegDO')
```

We are making some minor changes to the package on the [sine](https://github.com/fawda123/WtRegDO/tree/sine) branch that may include a fix for this error.

**Comment by KenishaS** [comment]
Thank you, that worked!

-Kenisha
